version: "3.9"
services:
  frontend:
    image: nschnierer/digital-peaks-web-aoa-frontend:latest
    container_name: "frontend"
    environment:
      - NODE_ENV
      - API_URL
    networks:
      - default

  api:
    image: nschnierer/digital-peaks-web-aoa-api:latest
    container_name: "api"
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["$API_COMMAND"]
    environment:
      - EXPRESS_PORT=9000
      - NODE_ENV
      - MONGODB_CONNECTION_STRING
      - JWT_SECRET
      - API_KEY
      - MAX_UPLOAD_FILE_SIZE_MB
      - API_URL
    volumes:
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
      - ./r:/app/r
      - ./jobs:/app/jobs
    networks:
      - default
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: "mongodb"
    restart: always
    ports:
      - "27017-27019:27017-27019"
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
      # will be used by the init-mongo.js file
      - MONGO_INITDB_API_USERNAME
      - MONGO_INITDB_API_PASSWORD
    volumes:
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo/volume:/data/db
    networks:
      - default

  haproxy:
    image: haproxy:2.5
    ports:
      - "${HAPROXY_PORT:-80}:8080"
    volumes:
      - ./ops/haproxy:/etc/haproxy/configs:ro
      - ${HAPROXY_CERT:-./ops/haproxy/cert.pem}:/etc/ssl/cert.pem:ro
    command:
      [
        "haproxy",
        "-f",
        "/etc/haproxy/configs/haproxy.cfg",
        "-f",
        "/etc/haproxy/configs/haproxy.${HAPROXY_CONFIG:-local}.cfg",
      ]
    depends_on:
      - api
      - frontend

  migration:
    profiles:
      - migration
    image: node:16-alpine
    container_name: "migration"
    restart: always
    command: ["/migration/create-user.js"]
    environment:
      - API_HOST=api
      - EXPRESS_PORT=9000
      - API_KEY
    volumes:
      - ./migration/create-user.js:/migration/create-user.js:ro
    networks:
      - default
    depends_on:
      - api

networks:
  default:
    driver: bridge
